package cmd

import (
	"bufio"
	"context"
	"fmt"
	"os"
	"strings"
	"time"

	"connectrpc.com/connect"
	libopsv1 "github.com/libops/proto/libops/v1"
	"github.com/libops/sitectl-libops/pkg/api"
	"github.com/libops/sitectl-libops/pkg/auth"
	"github.com/spf13/cobra"
)

var loginCmd = &cobra.Command{
	Use:   "login",
	Short: "Authenticate with the libops API",
	Long: `Authenticate with the libops API.

This command opens a browser window where you can choose to authenticate with:
- Google OAuth
- Email and password

After successful authentication, your credentials will be stored locally in ~/.sitectl/oauth.json.

Examples:
  sitectl libops login                                    # Open browser to login page
  sitectl libops login --api-url https://api.libops.io   # Use a custom API URL`,
	RunE: func(cmd *cobra.Command, args []string) error {
		flags := cmd.Flags()

		apiURL, err := flags.GetString("api-url")
		if err != nil {
			return fmt.Errorf("failed to get api-url flag: %w", err)
		}

		timeout, err := flags.GetDuration("timeout")
		if err != nil {
			return fmt.Errorf("failed to get timeout flag: %w", err)
		}

		// Create context with timeout
		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		fmt.Println("Opening browser for authentication...")
		fmt.Println("You can choose to sign in with Google or email/password in the browser.")

		// Create unified OAuth client
		authClient := auth.NewAuthClient(apiURL)
		tokens, err := authClient.Login(ctx)
		if err != nil {
			return fmt.Errorf("authentication failed: %w", err)
		}

		// Save tokens to disk
		if err := auth.SaveTokens(tokens); err != nil {
			return fmt.Errorf("failed to save authentication credentials: %w", err)
		}

		tokenPath, _ := auth.TokenFilePath()
		fmt.Printf("\n✓ Successfully authenticated!\n")
		fmt.Printf("Credentials saved to: %s\n", tokenPath)

		// Display token expiry
		expiryTime := time.Unix(tokens.ExpiryDate, 0)
		fmt.Printf("Token expires: %s\n", expiryTime.Format(time.RFC1123))

		// Check if API key already exists
		keyPath, err := auth.APIKeyFilePath()
		if err != nil {
			return fmt.Errorf("failed to resolve API key path: %w", err)
		}
		if _, err := os.Stat(keyPath); err == nil {
			fmt.Printf("\nAPI key already exists at: %s\n", keyPath)
			return nil
		}

		// Prompt user to create API key
		fmt.Println("\n" + strings.Repeat("-", 60))
		fmt.Println("Would you like to create an API key for future authentication?")
		fmt.Println("This will allow you to skip the login flow in the future.")
		fmt.Print("Create API key? [y/N]: ")

		reader := bufio.NewReader(os.Stdin)
		response, err := reader.ReadString('\n')
		if err != nil {
			return fmt.Errorf("failed to read input: %w", err)
		}

		response = strings.TrimSpace(strings.ToLower(response))
		if response != "y" && response != "yes" {
			fmt.Println("Skipping API key creation")
			return nil
		}

		// Create API key
		fmt.Println("\nCreating API key...")
		keyName := fmt.Sprintf("sitectl_%s", time.Now().Format("2006-01-02_15-04-05"))

		client, err := api.NewLibopsAPIClient(ctx, apiURL)
		if err != nil {
			return fmt.Errorf("failed to create API client: %w", err)
		}

		resp, err := client.AccountService.CreateApiKey(ctx, connect.NewRequest(&libopsv1.CreateApiKeyRequest{
			Name:        keyName,
			Description: "Auto-generated by sitectl libops login",
			Scopes:      []string{}, // Full scope
		}))
		if err != nil {
			return fmt.Errorf("failed to create API key: %w", err)
		}

		// Save API key to ~/.sitectl/key
		keyPath, err = auth.SaveAPIKey(resp.Msg.ApiKey)
		if err != nil {
			return fmt.Errorf("failed to save API key: %w", err)
		}

		fmt.Printf("\n✓ API key created successfully!\n")
		fmt.Printf("  Name: %s\n", keyName)
		fmt.Printf("  ID: %s\n", resp.Msg.ApiKeyId)
		fmt.Printf("  Stored at: %s\n", keyPath)
		fmt.Println("\nYou can now use sitectl commands without logging in again.")

		return nil
	},
}

var logoutCmd = &cobra.Command{
	Use:   "logout",
	Short: "Remove local authentication credentials",
	Long: `Remove local authentication credentials.

This command removes the locally stored OAuth tokens from ~/.sitectl/oauth.json
and the API key from ~/.sitectl/key.
You will need to run 'sitectl libops login' again to authenticate.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		tokenPath, err := auth.TokenFilePath()
		if err != nil {
			return fmt.Errorf("failed to get token path: %w", err)
		}

		keyPath, err := auth.APIKeyFilePath()
		if err != nil {
			return fmt.Errorf("failed to resolve API key path: %w", err)
		}

		removedAny := false

		// Remove token file
		if _, err := os.Stat(tokenPath); err == nil {
			if err := auth.ClearTokens(); err != nil {
				return fmt.Errorf("failed to remove credentials: %w", err)
			}
			fmt.Printf("Removed OAuth tokens from: %s\n", tokenPath)
			removedAny = true
		}

		// Remove API key file
		if _, err := os.Stat(keyPath); err == nil {
			if err := auth.ClearAPIKey(); err != nil {
				return fmt.Errorf("failed to remove API key: %w", err)
			}
			fmt.Printf("Removed API key from: %s\n", keyPath)
			removedAny = true
		}

		if !removedAny {
			fmt.Println("No authentication credentials found")
			return nil
		}

		fmt.Println("\n✓ Successfully logged out")

		return nil
	},
}

var whoamiCmd = &cobra.Command{
	Use:   "whoami",
	Short: "Display current authentication status",
	Long: `Display current authentication and development access status.

This command shows information about your current authentication session,
including token expiry, API key availability, account details, GitHub username,
and whether LibOps has an SSH key for your account.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		apiURL, err := cmd.Flags().GetString("api-url")
		if err != nil {
			return err
		}

		tokens, err := auth.LoadTokens()
		apiKey, apiKeyErr := auth.LoadAPIKey()
		hasAPIKey := apiKeyErr == nil && strings.TrimSpace(apiKey) != ""
		if err != nil {
			tokens = nil
		}
		if tokens == nil && !hasAPIKey {
			fmt.Println("Authentication Status: not authenticated")
			fmt.Println("Run 'sitectl libops login' to authenticate.")
			return nil
		}

		fmt.Println("Authentication Status: authenticated")
		if hasAPIKey {
			keyPath, _ := auth.APIKeyFilePath()
			fmt.Printf("API Key: configured (%s)\n", keyPath)
		} else {
			fmt.Println("API Key: not configured")
		}

		if tokens != nil {
			fmt.Printf("Token Type: %s\n", tokens.TokenType)

			expiryTime := time.Unix(tokens.ExpiryDate, 0)
			fmt.Printf("Token Expires: %s\n", expiryTime.Format(time.RFC1123))

			if tokens.IsTokenExpired() {
				fmt.Println("Token Status: expired")
				fmt.Println("Run 'sitectl libops login' to re-authenticate.")
			} else {
				timeUntilExpiry := time.Until(expiryTime)
				fmt.Printf("Time Until Expiry: %s\n", timeUntilExpiry.Round(time.Minute))
			}

			if tokens.Scope != "" {
				fmt.Printf("Scopes: %s\n", tokens.Scope)
			}

			tokenPath, _ := auth.TokenFilePath()
			fmt.Printf("OAuth Credentials: %s\n", tokenPath)
		} else {
			fmt.Println("OAuth Credentials: not configured")
		}

		account, err := api.GetCurrentAccount(cmd.Context(), apiURL)
		if err != nil {
			fmt.Printf("\nAccount: unavailable (%v)\n", err)
			return nil
		}

		fmt.Printf("\nAccount ID: %s\n", account.ID)
		fmt.Printf("Email: %s\n", account.Email)
		if account.Name != "" {
			fmt.Printf("Name: %s\n", account.Name)
		}
		if account.GithubUsername != "" {
			fmt.Printf("GitHub Username: %s\n", account.GithubUsername)
		} else {
			fmt.Println("GitHub Username: missing")
			fmt.Println("Development Config: run 'sitectl libops account update --github-username <username>'.")
		}

		client, err := api.NewLibopsAPIClient(cmd.Context(), apiURL)
		if err != nil {
			fmt.Printf("LibOps SSH Keys: unavailable (%v)\n", err)
			return nil
		}
		keysResp, err := client.SshKeyService.ListSshKeys(cmd.Context(), connect.NewRequest(&libopsv1.ListSshKeysRequest{}))
		if err != nil {
			fmt.Printf("LibOps SSH Keys: unavailable (%v)\n", err)
			return nil
		}
		if len(keysResp.Msg.SshKeys) == 0 {
			fmt.Println("LibOps SSH Keys: none")
			fmt.Println("SSH Access: add a public key with 'sitectl libops create ssh-key --public-key-file ~/.ssh/id_ed25519.pub'.")
		} else {
			fmt.Printf("LibOps SSH Keys: %d configured\n", len(keysResp.Msg.SshKeys))
		}

		fmt.Println("GitHub Checkout: ensure the same SSH public key is also added to GitHub.")

		return nil
	},
}

func init() {
	// Login command flags
	loginCmd.Flags().Duration("timeout", 5*time.Minute, "Timeout for authentication flow")
}
