name: goreleaser

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    uses: libops/terraform-linux-packages/.github/workflows/reusable-goreleaser.yaml@6f39b1c35f31c258f34af155dd1b9c2046238558 # main
    permissions:
      contents: write
    secrets: inherit
    with:
      go-version: ">=1.26.3"
